---
- name: Instalar Opera Browser no Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Instalar o Opera Browser usando Chocolatey
      win_chocolatey:
        name: opera
        state: present
      become: yes
