---
- hosts: all
  become: true
  tasks:
    - name: Instalar o browser Opera
      win_package:
        name: opera
        state: present
  handlers:
    - name: Reiniciar o computador
      win_reboot:
        force: yes
