---
- name: Instalar o Opera Browser no Windows
  hosts: windows_hosts
  gather_facts: no
  tasks:
    - name: Download do instalador do Opera
      win_get_url:
        url: "https://download.opera.com/download/get/?partner=www&opsys=Windows"
        dest: C:\Temp\opera_installer.exe

    - name: Instalar o Opera
      win_command: C:\Temp\opera_installer.exe /silent

    - name: Remover o instalador do Opera
      win_file:
        path: C:\Temp\opera_installer.exe
        state: absent
