---
- name: Instalar o Opera Browser no Windows
  hosts: windows_hosts
  gather_facts: no
  tasks:
    - name: Copiar o instalador do Opera para o host Windows
      win_copy:
        src: /caminho/local/para/o/arquivo/opera_installer.exe
        dest: C:\Temp\opera_installer.exe

    - name: Instalar o Opera Browser
      win_shell: |
        $installArgs = "/Silent /InstallPath=C:\Program Files\Opera"
        Start-Process -Wait -FilePath "C:\Temp\opera_installer.exe" -ArgumentList $installArgs

    - name: Remover o instalador do Opera
      win_file:
        path: C:\Temp\opera_installer.exe
        state: absent
